In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# creates an array of default size 50 having equal defference 
# ........................including last number....................................
# Returns `num` evenly spaced samples, calculated over the
# np.linspace(start,stop,no_of_elements)
np.linspace(1,50,20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# can also generate non square matrix generate 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [6]:
# random sample between 0,1
b=np.random.rand(10)*10
b

array([6.07199612, 3.15986661, 1.12880247, 2.83460029, 1.33579652,
       9.52418237, 7.62964788, 1.52130573, 1.54208746, 1.24431758])

In [7]:
np.random.randint(1000)

123