In [1]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 5  1 19 18  5]
[14 16  2 17  4]


In [2]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [3]:
#increasing each elemnt by 1 using numpy
a = a + 1
a

array([ 6,  2, 20, 19,  6])

In [4]:
c = a + b
c

array([20, 18, 22, 36, 10])

In [5]:
d = a - b
d

array([ -8, -14,  18,   2,   2])

In [6]:
e = a * b
e

array([ 84,  32,  40, 323,  24])

In [7]:
f = a / b
f

array([ 0.42857143,  0.125     , 10.        ,  1.11764706,  1.5       ])

In [8]:

g = a // b
g

array([ 0,  0, 10,  1,  1])

In [9]:
h = a ** b
h

array([1054752768,      65536,        400, 1046123219,       1296])

In [10]:
print(a)
# a.sum gives summ of all elements of array
print(a.sum())

# mean gives average
print(a.mean())
print(a.min())

# argmin() is used to find the index of minimum number
print(a.argmin())
print(a.max())
print(a.argmax())


[ 6  2 20 19  6]
53
10.6
2
1
20
2


In [11]:
print(a)
print(b)
a > b
a < b
a == b

# logical_or(and,not) are logical operators 

print(np.logical_or(a, b))
print(np.logical_and(a, b))

a[2] = 0
print(a)
print(np.logical_not(a))

[ 6  2 20 19  6]
[14 16  2 17  4]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ 6  2  0 19  6]
[False False  True False False]
